/**
 * Report generator. Creates structured JSON + markdown reports from analysis findings.
 */

import type { StaticFinding } from "./analyzer/static.js";
import type { ScoreBreakdown } from "./analyzer/scorer.js";

export interface AuditReport {
  address: string;
  contractName: string;
  compilerVersion: string;
  sourceVerified: boolean;
  timestamp: string;
  score: ScoreBreakdown;
  findings: StaticFinding[];
  summary: string;
}

export function generateReport(
  address: string,
  contractName: string,
  compilerVersion: string,
  sourceVerified: boolean,
  score: ScoreBreakdown,
  findings: StaticFinding[]
): AuditReport {
  const summary = buildSummary(contractName, score, sourceVerified);

  return {
    address,
    contractName,
    compilerVersion,
    sourceVerified,
    timestamp: new Date().toISOString(),
    score,
    findings: findings.sort((a, b) => severityOrder(a.severity) - severityOrder(b.severity)),
    summary,
  };
}

function buildSummary(
  contractName: string,
  score: ScoreBreakdown,
  verified: boolean
): string {
  const lines: string[] = [];

  lines.push(`# Security Audit Report: ${contractName}`);
  lines.push("");
  lines.push(`**Risk Score:** ${score.riskScore}/100 (${score.riskLevel.toUpperCase()})`);
  lines.push(`**Source Verified:** ${verified ? "Yes" : "No"}`);
  lines.push(`**Total Findings:** ${score.totalFindings}`);
  lines.push("");

  if (score.criticalCount > 0) {
    lines.push(`- ${score.criticalCount} Critical findings`);
  }
  if (score.highCount > 0) {
    lines.push(`- ${score.highCount} High findings`);
  }
  if (score.mediumCount > 0) {
    lines.push(`- ${score.mediumCount} Medium findings`);
  }
  if (score.lowCount > 0) {
    lines.push(`- ${score.lowCount} Low findings`);
  }
  if (score.infoCount > 0) {
    lines.push(`- ${score.infoCount} Info findings`);
  }

  if (score.riskScore === 0 && verified) {
    lines.push("");
    lines.push("No significant security issues detected. Source code is verified on BSCScan.");
  }

  return lines.join("\n");
}

export function reportToMarkdown(report: AuditReport): string {
  const lines: string[] = [];

  lines.push(report.summary);
  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push("## Score Breakdown");
  lines.push("");
  lines.push(`| Component | Score |`);
  lines.push(`|-----------|-------|`);
  lines.push(`| Critical findings | ${report.score.criticalScore}/40 |`);
  lines.push(`| High findings | ${report.score.highScore}/25 |`);
  lines.push(`| Medium findings | ${report.score.mediumScore}/15 |`);
  lines.push(`| Unverified source | ${report.score.unverifiedScore}/10 |`);
  lines.push(`| Centralization risk | ${report.score.centralizationScore}/10 |`);
  lines.push(`| **Total** | **${report.score.riskScore}/100** |`);
  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push("## Findings");
  lines.push("");

  for (const finding of report.findings) {
    const icon = severityIcon(finding.severity);
    lines.push(`### ${icon} [${finding.severity.toUpperCase()}] ${finding.title}`);
    lines.push("");
    lines.push(`**ID:** ${finding.id}`);
    lines.push(`**Confidence:** ${finding.confidence}`);
    if (finding.line) lines.push(`**Line:** ${finding.line}`);
    if (finding.file) lines.push(`**File:** ${finding.file}`);
    lines.push("");
    lines.push(finding.description);
    lines.push("");
  }

  lines.push("---");
  lines.push("");
  lines.push(`*Report generated by Aegis Security Oracle on ${report.timestamp}*`);
  lines.push(`*Address: ${report.address}*`);

  return lines.join("\n");
}

function severityOrder(s: StaticFinding["severity"]): number {
  const order = { critical: 0, high: 1, medium: 2, low: 3, info: 4 };
  return order[s];
}

function severityIcon(s: StaticFinding["severity"]): string {
  const icons = { critical: "🔴", high: "🟠", medium: "🟡", low: "🔵", info: "⚪" };
  return icons[s];
}
